#!/bin/bash

whiptail --title "VPN Client Gateway firewall configuration" --yesno "Warning:\nDo you want to remove all firewall rules? The VPN Client Gateway will no longer forward traffic via VPN. This may affect other users on your network." --defaultno 10 62 3>&1 1>&2 2>&3
confirm=$?
if [ $confirm = 0 ]; then
	# delete all existing rules
	sudo iptables -Z
	sudo iptables --flush
	sudo iptables --delete-chain
	sudo iptables -t nat -F

	# default drop policy:
	sudo iptables --policy INPUT   ACCEPT;
	sudo iptables --policy OUTPUT  ACCEPT;
	sudo iptables --policy FORWARD ACCEPT;

	# save the firewall rules
	sudo su -c 'iptables-save > /etc/iptables/rules.v4'
	printf "\nWarning:\nAll firewall rules have been removed. Run fw-config to configure the firewall.\n\n"
fi



